### ISSUE TITLE
A checklist test

### ISSUE THREAD

**Issue by ybarkley** [nmfs-openscapes/2022-noaa-swfsc-pifsc-fall#23]
- [x] Send Kym an issue to look at - @kmyano 
- [x] Hopefully Kym looks at the issue
- [x] Then the issue can be closed and we all win!

**Comment by kmyano** [comment]
we all win!! Woo!!
